# Generated by Django 4.1.7 on 2023-02-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geotrainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='number',
        ),
        migrations.AddField(
            model_name='games',
            name='capitals',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='flags',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
